// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbrigrkmsjshhlrlukzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imticmlncmttc2pzaGhscmx1a3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzA5NjksImV4cCI6MjA3MjcwNjk2OX0.5xhoXt1agyqn6veV3oKD3eYKVuy61ekZez9rGg2YxpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});